### ISSUE TITLE
Stai doesn't sync nor connect to peers (v.1.3.2.dev2)

### ISSUE THREAD

**Issue by zwergholdrio** [STATION-I/staicoin-blockchain#33]
I updated to the latest version (v.1.3.2.dev2), checked if the db needs to update (which wasn't needed).

Started farmer (`stai start farmer`).

But it doesn't seem to sync nor connect to peers:
`Farming status: Not synced or not connected to peers`

**Comment by WarutaShinken** [comment]
Does this issue still exist? This was probably due to our introducer being down, which has been fixed.

**Comment by zwergholdrio** [comment]
I restarted farmer but the issue still seems to exist.

**Comment by WarutaShinken** [comment]
It might be another issue: A configuration from before 1.3.1.

Does the `dns_servers` under `full_node` only show `dns-introducer.staicoin.com`? If so, replace it with or add `introducer.staicoin.com`, or just delete the `config` directory and re-run `stai init`. 1.3.1 will generate a config that looks like this:

```
  dns_servers:
  - dns-introducer.staicoin.com
  - introducer.staicoin.com
```

If you're manually fixing it, I suggest doing the same under `wallet`.

The reason for doing this is because there are currently issues with the `dns-introducer.staicoin.com` domain. However, this should still mean that the legacy introducer on the second domain (both introducers run on the same server and therefore use the second domain too) works, although it appears to be a lot slower than the DNS introducer.

**Comment by zwergholdrio** [comment]
tried both scenarios (manually changing config.yaml and rm -r config with stai init)... both result in
`Daemon not started yet`
`Starting daemon`
`Daemon not started yet`
`Failed to create the stai daemon`

Probably will go ahead and install everything from scratch... :/

**Comment by WarutaShinken** [comment]
Let me know if it works afterwards so I can close the issue.

**Comment by WarutaShinken** [comment]
Closing as both introducers work, albeit with slow speeds.
